[filepush.cpp] Drop unused variable
Fix build with GCC 16.

| ../../sources/enigma2-3.14+git/lib/dvb/filepush.cpp: In member function 'int eFilePushThreadRecorder::read_dmx(int, void*, int)':
| ../../sources/enigma2-3.14+git/lib/dvb/filepush.cpp:437:13: error: variable 'it' set but not used [-Werror=unused-but-set-variable=]
|   437 |         int it = 0, pos = 0, bytes = 0;
|       |             ^~