[lcd.cpp] Fix build with Wrynose branch
Fix:

| ../../sources/enigma2-3.14+git/lib/gdi/lcd.cpp: In member function 'virtual void eDBoxLCD::update()':
| ../../sources/enigma2-3.14+git/lib/gdi/lcd.cpp:247:22: error: ignoring return value of '
ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   247 |                 write(lcdfd, raw, 132 * 8);
|       |                 ~~~~~^~~~~~~~~~~~~~~~~~~~~
| ../../sources/enigma2-3.14+git/lib/gdi/lcd.cpp:268:30: error: ignoring return value of
'ssize_t write(int, const void*, size_t)' declared with attribute 'warn_unused_result' [-Werror=unused-result]
|   268 |                         write(lcdfd, raw, _stride * height);
|       |                         ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~